version: '3'

services:
  XianyuAutoAgent:
    build: .
    image: xianyuautoagent:local
    container_name: xianyuautoagent
    restart: always
    volumes:
      - ./data:/app/data
      - ./prompts:/app/prompts
      - ./.env:/app/.env
    environment:
      - TZ=Asia/Shanghai
    networks:
      - xianyu-network

networks:
  xianyu-network:
    driver: bridge
